.TH POOLTYPE 1L  10/21/89
.SH NAME
pooltype - display a WEB pool file
.SH SYNOPSIS
.B pltotf
pool_file_name
.SH DESCRIPTION
.I POOLtype
translates a (program_readable) string pool file to a
(human-readable) text file.
.PP
The
.I pool_file_name
must be complete. No adding of default extensions is done.
.SH "SEE ALSO"
.br
Donald Knuth,
.I TeXware, The WEB system
.SH "AUTHORS"
Donald Knuth wrote the program and ported it to Unix. It was published as
part of the
.I TeXware
technical report (Stanford CS1097), available from TUG (the TeX Users Group).
