#! /bin/csh
# A shell script to perform modifications on the changefile for initex
# to make a changefile for triptex (used to test tex).
#
# To use it, say
#	ini_to_trip initex.ch triptex.ch
#
ed - $1 <<edscriptend
/debug=/
//
s/@{//p
/gubed=/
s/@t@>@}//p
/@!mem_max=/
//
s/[0-9][0-9]*/3000/p
/@!mem_min=/
s/-[0-9]*/1/p
/@!error_line=/
s/[0-9][0-9]*/64/p
/@!half_error_line=/
s/[0-9][0-9]*/32/p
/@!max_print_line=/
s/[0-9][0-9]*/72/p
/@!font_max=/
s/[0-9][0-9]*/75/p
/@!font_mem_size=/
s/[0-9][0-9]*/20000/p
/@!pool_size=/
s/[0-9][0-9]*/32000/p
/@d mem_bot=/
//
s/-[0-9]*/1/p
/@d mem_top==/
s/[0-9][0-9]*/3000/p
/@d hash_size=/
s/[0-9][0-9]*/2100/p
/@d hash_prime=/
s/[0-9][0-9]*/1777/p
w $2
edscriptend
